FROM node:alpine

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install

# if used prisma then generate client over here

RUN npm run build

CMD [ "npm", "run", "start-user-app" ]