name: Build on PR

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        name: build the project
        runs-on: ubuntu-latest

        steps:
            - name: cloning project
              uses: actions/checkout@v3

            - name: using node js
              uses: actions/setup-node@v3
              with:
                    node-version: '23'
            
            - name: install dependencies
              run: npm install

            - name: building the project
              run: npm run build
            
        
