name: create docker image on code push

on:
    push:
        branches:
                - main

jobs:
    build-and-push:
            runs-on: ubuntu-lastest
            steps:
                - name: check out repo
                  uses: actions/checkout@v3
                
                - name: log into docker hub
                  uses: docker/login-action@v1
                  with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_SECRET }}

                - name: build and push docker image
                  uses: docker/build-push-action@v2
                  with:
                        context: .
                        file: ./Docker/Dockerfile.user
                        push: true
                        tags: startest/next_ci-cd_test
                
                - name: verify push image
                  run: docker pull startest/next_ci-cd_test